name: lint and test when PR

on:
  pull_request:
    branches: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.16'
          cache-dependency-path: go.mod

      - name: Go lint
        uses: golangci/golangci-lint-action@v6

      - name: Go test
        run: go test -v ./...
